name: Build Vue project

on:
  push:
    branches:
      - 'main'
      - 'feature/*'
    tags:
      - '*'
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
          node-version: '18'
    - name: Check node version
      run: node --version

    - name: Prepare project
      run: npm install
    - name: Build project
      run: npm run build --if-present
    - name: Run Unit-Tests
      run: npm run test:unit
