name: Build Vue project

on:
  push:
    branches:
      - 'main'
      - 'feature/*'
    tags:
      - '*'
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate variables
      run: |
        echo "Head Ref: $GITHUB_HEAD_REF"
        echo "Full Ref: $GITHUB_REF"
        echo "Full Ref name: $GITHUB_REF_NAME"
        _GIT_SHORT=$(git rev-parse --short HEAD)
        _GITHUB_RUN_DATE=$(date '+%d-%m-%Y_%H:%M:%S')
        echo "_BUILD_VERSION=${GITHUB_REF_NAME}_${_GITHUB_RUN_DATE}_${_GIT_SHORT}" >> $GITHUB_ENV
    - name: Read variables
      run: |
        echo "Build version: ${_BUILD_VERSION}"