name: Build Vue project

on:
  push:
    branches:
      - 'main'
      - 'feature/*'
    tags:
      - '*'
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate variables
      run: |
        echo "Head Ref: $GITHUB_HEAD_REF"
        echo "Full Ref: $GITHUB_REF"
        echo "Full Ref name: $GITHUB_REF_NAME"
        GIT_SHORT=$(git rev-parse --short HEAD)
        echo "Git Short: $GIT_SHORT"